### ISSUE TITLE
Fix TODO in 0.9.41

### ISSUE THREAD

**Issue by zjb0807** [shaunxw/xcm-simulator#46]
TODO

_Originally posted by @zjb0807 in https://github.com/shaunxw/xcm-simulator/pull/44#discussion_r1125959595_

**Comment by ntn-x2** [comment]
What's up with this ticket? xcm-emulator seems to be stuck on 0.9.40 support?

**Comment by zjb0807** [comment]
https://github.com/paritytech/polkadot/pull/6824 This PR has not been merged yet. 

Parity integrates the `xcm-emulator` into cumulus, it can be used since 0.9.43
https://github.com/paritytech/cumulus/pull/2447

**Comment by ntn-x2** [comment]
Ok so it's not worth merging https://github.com/shaunxw/xcm-simulator/pull/51 which brings support to 0.9.41? What if some teams are on either 0.9.41 or 0.9.42? Just asking for info since that's exactly the situation we are in! We might have a new release based on 0.9.42, and would need to have xcm-emulator support that.
